server:
  port: 8003
spring:
  application:
    name: sms-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.6.100
    port: 9990
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0

#      日志级别
logging:
  level:
    root: info
#     开启熔断机制
