server:
  port: 8007
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeout_food?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1477112645
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath:/com/haven/orderservice/mapper/xml/*.xml

#      日志级别
logging:
  level:
    root: info
#     开启熔断机制
feign:
  hystrix:
    enabled: true
#    设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
#设置支付宝接入的信息
alipay:
  appId: 2021000118624396
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCn1QBZyVpXQhS+ax6d4purEyNJd1f/2nIKLRwczOho5kX3S8q1dQ+rnlLiiF8L7tneXE7ZY6ciZ4Aw7GQgH5iNa3GSrf04GEW+/izPe6iw+wJ6VRGTXsFWRLhjMe/vJAmcso3wp9QKPv54K+2BX9kzGj+ZXKQaHlp7HEj7Od6bUCdjcEryMoxCdi/Gcf/NCMorhJxRNiFkF3rlTnH8Cc5BFAjQeUGdjjms/bFXlpmKoUB+XzF1MmdGPFqs+EE2XzOYt0/tZFyott7QLgGRPkbcU6ihcX4IcuZc2POnz9/IGWtjj1wKm0VSLMISGvXKPmbRhizHNG8KJlE90dH0H33XAgMBAAECggEAJf2WRbzJgWUI8w2mcZDhMfl0DGZCej0FgX4yleZgWZZ+kfsLGMY11OBS3MqH0Viw4p+8jYL8S1Jodyqbg5YDX0fJ/qz529/KsfAxToosZlt7dRuajeRuGUwW/QVJzbU3o8vbS3WCDwuxaJxw988tiF7RtLJ+xxbF3oZJkuzHkhpUzOt5a8SKYxxKQ+T40qqLQEoNfqQmiBkThGqadlLx/+RtgEpH9JIR1kf91I336thyanduAUSRKdrBmOPla92i6MUz6ZPHmG1+j2uW3ftyOkq+aAI24MWvqjhBOnRtEHWDh+BSYOMsTGBx10SMT6/JolEqfoMUD+oLPeYyxITiyQKBgQDxr92QbYxHfLPcRS9w0kcLNYd2ZZPdm2+w6zgWY1ecfP0+z88RmlWXbe3YH8DHF/aPe/SdfHqROvigW8wWcC0ZWogAkP65MVB03OYhuyDF6ahTnhT/n5cQBCm/apvHt7MRbmy9VigxC5BpFjvSQD2lqWawsaO/3PxfarsYqVN2rQKBgQCxxXI2I7QE9spTo8lAEmRSHB7WJiOz5RnTlIxO2F2QIJOQXuxp6SEFFd+mMtEsAyYoOAAY67bPfxvXG2SOUFDOQW1V1f3WeRbyrMkRmB/hqGXYbPFrUvwrHKaELReGisXZVpXNd2L1XCa5PtrHuwJ5gYhE9I+WU8PIlSFgde1LEwKBgHYCaS0cUGKXgTsMjR2Jjybp/DrTXl/WhbLdJ4XG/ABtBzqkPXda5HAMPRZKatbL3Jgy7j33ieFf6gZizEQogdzfV4jvQ3Epox9svPG7bUU10fsCNT6bricj4T6Vz3q1N7pLMM1CRF2uR9UIBi2jMHazQHEGS+5i+NeeRbzE8PwBAoGAbtsVkbVJ+R58pROp2A6gCKQIhrpZ4UCojkxAApriHZJy8sB+5LzAHo+5W8assal1Dfd9+Axlf5dgIQ+v8R8chMJAEBrVo/z21nXxHMukde+xMvkcwzSIk8nV/O6xkPDQ1+sql2ovh5nje/k6LPrtXB/ufjGTqMarfFWi7qgbRYkCgYEAzk78CJOyBI3/BuEIeCW27WTpcfKXX2JtNrt8YhrL57raNUfrdevXqtp8WyzuCRoXmahF6FLo6fpqNy+G6D08yspN2fw3e2TsB08Rj4/7jWCp4izffT/5yVgd+1QPn9S0pZK6zDKHMa7T4YTeepRXW9wXmnBkDxO5nCPmfMnoJbU=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiZw5nBQ2HBu8cSuOcHFwtJLnFzsXABMbekqBgMNmA4wc0J1vxeQs2Bqj9Il16GofwolXASLcVydoRyMhI8YXJ1LV1z3T4ITRz9ziCjNoZAAfUsii3ppXLMoW13OudKBD9UcfHskXHtyENUcniwlUPrfXHy1cVOUf1EfDKf2n/v7D0Ri8IBFy1TcwIWZjpihiguQHQy2su4Wf+lUpc70rgLvw7dIP5wahnSYt9Lwzsc+LZ743FQQ6zKrorQGP0z72LfnMusY2hMCLUuWXPZypjVoiNLqNQLv04+Rhs7oG4DxmP+2xRjhBgCL95b7C3G/CSHhD08MoP/fKUiPujIPlqwIDAQAB
  notifyUrl: http://havenlin.nat300.top/alipay/notify